version: "3.7"

services:
  go:
    image: cyradin/go:1.19
    volumes:
      - ".:/home/user/app:rw"
      - "go-pkg:/home/user/go/pkg:rw"
      - "go-bin:/home/user/go/bin:rw"

volumes:
  go-pkg:
    driver: local
  go-bin:
    driver: local
